added unique parameter to members that needed it for db
seng499-company1/backend pull request #81
Opened 2022-07-05 17:15 UTC by owenjaques

# Description
This PR is pretty small as it just adds unique keys to fields I felt needed it in the DB. 

Fixes #77 
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# How Has This Been Tested?
- [ ] Ran docker with new changes and it worked
# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have linted my code and fixed all issues

2022-07-05 17:19 UTC, owenjaques commented
Ahhh test is failing now, please don't merge this. I will figure out what is going on.

2022-07-06 19:09 UTC, itsazoo requested changes
Is it possible to have a unique constaint on a pair? For ProfessorAvailability, profs should only have one entry per year. Therefore (prof_id, year) should be a unique pair. Similarly, in ProfessorCoursePreference (course_id, prof_avail_id) should be a unique pair. 
Everything else looks good!

2022-07-06 19:12 UTC, itsazoo commented
> Is it possible to have a unique constaint on a pair? For ProfessorAvailability, profs should only have one entry per year. Therefore (prof_id, year) should be a unique pair. Similarly, in ProfessorCoursePreference (course_id, prof_avail_id) should be a unique pair.
> Everything else looks good!
Looks like this might do the trick. (https://stackoverflow.com/questions/635937/how-do-i-specify-unique-constraint-for-multiple-columns-in-mysql)
`UNIQUE KEY `my_uniq_id` (`course_id `,`prof_avail_id `)`

2022-07-18 23:04 UTC, itsazoo requested changes

2022-07-18 23:04 UTC, itsazoo commented on database/sql/schema.sql
>  	min_offering INT NOT NULL,
We now support saving historical preferences for profs therefore we need to add a unique constraint in ProfessorAvailability table: 

- [ ] Add `UNIQUE KEY `my_uniq_id` (`year`,`prof_id`)` to ProfessorAvilability table

2022-07-29 05:42 UTC, itsazoo commented
Are we still planning to add this functionality?

2022-07-29 05:46 UTC, ekanemeinstein commented
Out of scope

2022-07-29 05:46 UTC, closed without merging